/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  mutation registerBroadcaster($input: RegisterBroadcasterInput!) {\n    registerBroadcaster(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          city\n          street\n        }\n      }\n    }\n  }\n": typeof types.RegisterBroadcasterDocument,
    "\n  mutation registerClient($input: RegisterClientInput!) {\n    registerClient(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          city\n          street\n        }\n        ... on Client {\n          agency {\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.RegisterClientDocument,
    "\n  mutation googleAuth($code: String!) {\n    googleAuth(input: { code: $code }) {\n      token\n      requiresRegistration\n      subject\n      email\n      firstName\n      lastName\n    }\n  }\n": typeof types.GoogleAuthDocument,
    "\n  mutation login($input: UserLoginInput!) {\n    login(input: $input) {\n      token\n      user {\n        userId\n        email\n        firstName\n        lastName\n        __typename\n      }\n    }\n  }\n": typeof types.LoginDocument,
    "\n  mutation completeGoogleSignUpBroadcaster(\n    $input: CompleteGoogleSignUpBroadcasterInput!\n  ) {\n    completeGoogleSignUpBroadcaster(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          street\n          city\n        }\n      }\n    }\n  }\n": typeof types.CompleteGoogleSignUpBroadcasterDocument,
    "\n  mutation completeGoogleSignUpClient(\n    $input: CompleteGoogleSignUpClientInput!\n  ) {\n    completeGoogleSignUpClient(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          street\n          city\n        }\n        ... on Client {\n          agency {\n            name\n          }\n        }\n      }\n    }\n  }\n": typeof types.CompleteGoogleSignUpClientDocument,
    "\n  query contracts($first: Int, $after: String) {\n    contracts(first: $first, after: $after) {\n      nodes {\n        contractId\n        broadcaster {\n          firstName\n          lastName\n        }\n        client {\n          firstName\n          lastName\n          agency {\n            name\n          }\n        }\n        state\n        date\n        dueDate\n      }\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      totalCount\n    }\n  }\n": typeof types.ContractsDocument,
    "\n  query contractsFiltered($first: Int, $after: String, $state: ContractState!) {\n    contracts(first: $first, after: $after, where: { state: { eq: $state } }) {\n      nodes {\n        contractId\n        broadcaster {\n          firstName\n          lastName\n        }\n        client {\n          firstName\n          lastName\n          agency {\n            name\n          }\n        }\n        state\n        date\n        dueDate\n      }\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      totalCount\n    }\n  }\n": typeof types.ContractsFilteredDocument,
    "\n  mutation UpdateContractState($input: UpdateContractStateInput!) {\n    updateContractState(input: $input) {\n      contractId\n      state\n      broadcaster {\n        firstName\n        lastName\n      }\n      client {\n        firstName\n        lastName\n      }\n    }\n  }\n": typeof types.UpdateContractStateDocument,
    "\n  mutation GenerateContract($input: CampaignInput!) {\n    generateContract(input: $input) {\n      client {\n        firstName\n        lastName\n      }\n    }\n  }\n": typeof types.GenerateContractDocument,
    "\n  query countries {\n    countries {\n      countryCode\n      name\n    }\n  }\n": typeof types.CountriesDocument,
    "\n  query departments($countryCode: String!) {\n    departments(where: { countryCode: { eq: $countryCode } }) {\n      departmentId\n      name\n    }\n  }\n": typeof types.DepartmentsDocument,
    "\n  query services {\n    services {\n      type\n      name\n      serviceId\n      basePrice\n      extraPrice\n      firstExtraPrice\n      __typename\n      ... on ServiceNarrative {\n        rolePrice\n      }\n      ... on ServiceIvr {\n        additionalMessagePrice\n      }\n      ... on ServicePeriod {\n        periods(order: { basePrice: ASC }) {\n          basePrice\n          extraPrice\n          firstExtraPrice\n          interval\n        }\n      }\n    }\n  }\n": typeof types.ServicesDocument,
    "\n  query CalculateContract($input: CampaignInput!) {\n    calculateContract(input: $input) {\n      total\n      beforeDiscount\n      adjustments {\n        name\n        key\n        type\n        amount\n        applyDiscount\n      }\n      services {\n        pieces {\n          name\n          price\n        }\n        serviceName\n        basePrice\n        subsequentPrice\n        adjustments {\n          name\n          key\n          type\n          amount\n          applyDiscount\n        }\n        subTotal\n        beforeDiscount\n      }\n    }\n  }\n": typeof types.CalculateContractDocument,
    "\n  query clients($firstName: String!, $lastName: String!) {\n    clients(where: { firstName: { eq: $firstName }, lastName: { eq: $lastName } }) {\n      userId\n      firstName\n      lastName\n    }\n  }\n": typeof types.ClientsDocument,
    "\n  query broadcasters($firstName: String!, $lastName: String!) {\n    broadcasters(where: { firstName: { eq: $firstName }, lastName: { eq: $lastName } }) {\n      userId\n      firstName\n      lastName\n    }\n  }\n": typeof types.BroadcastersDocument,
};
const documents: Documents = {
    "\n  mutation registerBroadcaster($input: RegisterBroadcasterInput!) {\n    registerBroadcaster(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          city\n          street\n        }\n      }\n    }\n  }\n": types.RegisterBroadcasterDocument,
    "\n  mutation registerClient($input: RegisterClientInput!) {\n    registerClient(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          city\n          street\n        }\n        ... on Client {\n          agency {\n            name\n          }\n        }\n      }\n    }\n  }\n": types.RegisterClientDocument,
    "\n  mutation googleAuth($code: String!) {\n    googleAuth(input: { code: $code }) {\n      token\n      requiresRegistration\n      subject\n      email\n      firstName\n      lastName\n    }\n  }\n": types.GoogleAuthDocument,
    "\n  mutation login($input: UserLoginInput!) {\n    login(input: $input) {\n      token\n      user {\n        userId\n        email\n        firstName\n        lastName\n        __typename\n      }\n    }\n  }\n": types.LoginDocument,
    "\n  mutation completeGoogleSignUpBroadcaster(\n    $input: CompleteGoogleSignUpBroadcasterInput!\n  ) {\n    completeGoogleSignUpBroadcaster(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          street\n          city\n        }\n      }\n    }\n  }\n": types.CompleteGoogleSignUpBroadcasterDocument,
    "\n  mutation completeGoogleSignUpClient(\n    $input: CompleteGoogleSignUpClientInput!\n  ) {\n    completeGoogleSignUpClient(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          street\n          city\n        }\n        ... on Client {\n          agency {\n            name\n          }\n        }\n      }\n    }\n  }\n": types.CompleteGoogleSignUpClientDocument,
    "\n  query contracts($first: Int, $after: String) {\n    contracts(first: $first, after: $after) {\n      nodes {\n        contractId\n        broadcaster {\n          firstName\n          lastName\n        }\n        client {\n          firstName\n          lastName\n          agency {\n            name\n          }\n        }\n        state\n        date\n        dueDate\n      }\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      totalCount\n    }\n  }\n": types.ContractsDocument,
    "\n  query contractsFiltered($first: Int, $after: String, $state: ContractState!) {\n    contracts(first: $first, after: $after, where: { state: { eq: $state } }) {\n      nodes {\n        contractId\n        broadcaster {\n          firstName\n          lastName\n        }\n        client {\n          firstName\n          lastName\n          agency {\n            name\n          }\n        }\n        state\n        date\n        dueDate\n      }\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      totalCount\n    }\n  }\n": types.ContractsFilteredDocument,
    "\n  mutation UpdateContractState($input: UpdateContractStateInput!) {\n    updateContractState(input: $input) {\n      contractId\n      state\n      broadcaster {\n        firstName\n        lastName\n      }\n      client {\n        firstName\n        lastName\n      }\n    }\n  }\n": types.UpdateContractStateDocument,
    "\n  mutation GenerateContract($input: CampaignInput!) {\n    generateContract(input: $input) {\n      client {\n        firstName\n        lastName\n      }\n    }\n  }\n": types.GenerateContractDocument,
    "\n  query countries {\n    countries {\n      countryCode\n      name\n    }\n  }\n": types.CountriesDocument,
    "\n  query departments($countryCode: String!) {\n    departments(where: { countryCode: { eq: $countryCode } }) {\n      departmentId\n      name\n    }\n  }\n": types.DepartmentsDocument,
    "\n  query services {\n    services {\n      type\n      name\n      serviceId\n      basePrice\n      extraPrice\n      firstExtraPrice\n      __typename\n      ... on ServiceNarrative {\n        rolePrice\n      }\n      ... on ServiceIvr {\n        additionalMessagePrice\n      }\n      ... on ServicePeriod {\n        periods(order: { basePrice: ASC }) {\n          basePrice\n          extraPrice\n          firstExtraPrice\n          interval\n        }\n      }\n    }\n  }\n": types.ServicesDocument,
    "\n  query CalculateContract($input: CampaignInput!) {\n    calculateContract(input: $input) {\n      total\n      beforeDiscount\n      adjustments {\n        name\n        key\n        type\n        amount\n        applyDiscount\n      }\n      services {\n        pieces {\n          name\n          price\n        }\n        serviceName\n        basePrice\n        subsequentPrice\n        adjustments {\n          name\n          key\n          type\n          amount\n          applyDiscount\n        }\n        subTotal\n        beforeDiscount\n      }\n    }\n  }\n": types.CalculateContractDocument,
    "\n  query clients($firstName: String!, $lastName: String!) {\n    clients(where: { firstName: { eq: $firstName }, lastName: { eq: $lastName } }) {\n      userId\n      firstName\n      lastName\n    }\n  }\n": types.ClientsDocument,
    "\n  query broadcasters($firstName: String!, $lastName: String!) {\n    broadcasters(where: { firstName: { eq: $firstName }, lastName: { eq: $lastName } }) {\n      userId\n      firstName\n      lastName\n    }\n  }\n": types.BroadcastersDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation registerBroadcaster($input: RegisterBroadcasterInput!) {\n    registerBroadcaster(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          city\n          street\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation registerBroadcaster($input: RegisterBroadcasterInput!) {\n    registerBroadcaster(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          city\n          street\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation registerClient($input: RegisterClientInput!) {\n    registerClient(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          city\n          street\n        }\n        ... on Client {\n          agency {\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation registerClient($input: RegisterClientInput!) {\n    registerClient(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          city\n          street\n        }\n        ... on Client {\n          agency {\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation googleAuth($code: String!) {\n    googleAuth(input: { code: $code }) {\n      token\n      requiresRegistration\n      subject\n      email\n      firstName\n      lastName\n    }\n  }\n"): (typeof documents)["\n  mutation googleAuth($code: String!) {\n    googleAuth(input: { code: $code }) {\n      token\n      requiresRegistration\n      subject\n      email\n      firstName\n      lastName\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation login($input: UserLoginInput!) {\n    login(input: $input) {\n      token\n      user {\n        userId\n        email\n        firstName\n        lastName\n        __typename\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation login($input: UserLoginInput!) {\n    login(input: $input) {\n      token\n      user {\n        userId\n        email\n        firstName\n        lastName\n        __typename\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation completeGoogleSignUpBroadcaster(\n    $input: CompleteGoogleSignUpBroadcasterInput!\n  ) {\n    completeGoogleSignUpBroadcaster(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          street\n          city\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation completeGoogleSignUpBroadcaster(\n    $input: CompleteGoogleSignUpBroadcasterInput!\n  ) {\n    completeGoogleSignUpBroadcaster(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          street\n          city\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation completeGoogleSignUpClient(\n    $input: CompleteGoogleSignUpClientInput!\n  ) {\n    completeGoogleSignUpClient(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          street\n          city\n        }\n        ... on Client {\n          agency {\n            name\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation completeGoogleSignUpClient(\n    $input: CompleteGoogleSignUpClientInput!\n  ) {\n    completeGoogleSignUpClient(input: $input) {\n      token\n      user {\n        __typename\n        email\n        firstName\n        lastName\n        rut\n        address {\n          country {\n            countryCode\n            name\n          }\n          department {\n            departmentId\n            name\n          }\n          street\n          city\n        }\n        ... on Client {\n          agency {\n            name\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query contracts($first: Int, $after: String) {\n    contracts(first: $first, after: $after) {\n      nodes {\n        contractId\n        broadcaster {\n          firstName\n          lastName\n        }\n        client {\n          firstName\n          lastName\n          agency {\n            name\n          }\n        }\n        state\n        date\n        dueDate\n      }\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      totalCount\n    }\n  }\n"): (typeof documents)["\n  query contracts($first: Int, $after: String) {\n    contracts(first: $first, after: $after) {\n      nodes {\n        contractId\n        broadcaster {\n          firstName\n          lastName\n        }\n        client {\n          firstName\n          lastName\n          agency {\n            name\n          }\n        }\n        state\n        date\n        dueDate\n      }\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      totalCount\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query contractsFiltered($first: Int, $after: String, $state: ContractState!) {\n    contracts(first: $first, after: $after, where: { state: { eq: $state } }) {\n      nodes {\n        contractId\n        broadcaster {\n          firstName\n          lastName\n        }\n        client {\n          firstName\n          lastName\n          agency {\n            name\n          }\n        }\n        state\n        date\n        dueDate\n      }\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      totalCount\n    }\n  }\n"): (typeof documents)["\n  query contractsFiltered($first: Int, $after: String, $state: ContractState!) {\n    contracts(first: $first, after: $after, where: { state: { eq: $state } }) {\n      nodes {\n        contractId\n        broadcaster {\n          firstName\n          lastName\n        }\n        client {\n          firstName\n          lastName\n          agency {\n            name\n          }\n        }\n        state\n        date\n        dueDate\n      }\n      pageInfo {\n        hasNextPage\n        hasPreviousPage\n        startCursor\n        endCursor\n      }\n      totalCount\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateContractState($input: UpdateContractStateInput!) {\n    updateContractState(input: $input) {\n      contractId\n      state\n      broadcaster {\n        firstName\n        lastName\n      }\n      client {\n        firstName\n        lastName\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateContractState($input: UpdateContractStateInput!) {\n    updateContractState(input: $input) {\n      contractId\n      state\n      broadcaster {\n        firstName\n        lastName\n      }\n      client {\n        firstName\n        lastName\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation GenerateContract($input: CampaignInput!) {\n    generateContract(input: $input) {\n      client {\n        firstName\n        lastName\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation GenerateContract($input: CampaignInput!) {\n    generateContract(input: $input) {\n      client {\n        firstName\n        lastName\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query countries {\n    countries {\n      countryCode\n      name\n    }\n  }\n"): (typeof documents)["\n  query countries {\n    countries {\n      countryCode\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query departments($countryCode: String!) {\n    departments(where: { countryCode: { eq: $countryCode } }) {\n      departmentId\n      name\n    }\n  }\n"): (typeof documents)["\n  query departments($countryCode: String!) {\n    departments(where: { countryCode: { eq: $countryCode } }) {\n      departmentId\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query services {\n    services {\n      type\n      name\n      serviceId\n      basePrice\n      extraPrice\n      firstExtraPrice\n      __typename\n      ... on ServiceNarrative {\n        rolePrice\n      }\n      ... on ServiceIvr {\n        additionalMessagePrice\n      }\n      ... on ServicePeriod {\n        periods(order: { basePrice: ASC }) {\n          basePrice\n          extraPrice\n          firstExtraPrice\n          interval\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query services {\n    services {\n      type\n      name\n      serviceId\n      basePrice\n      extraPrice\n      firstExtraPrice\n      __typename\n      ... on ServiceNarrative {\n        rolePrice\n      }\n      ... on ServiceIvr {\n        additionalMessagePrice\n      }\n      ... on ServicePeriod {\n        periods(order: { basePrice: ASC }) {\n          basePrice\n          extraPrice\n          firstExtraPrice\n          interval\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CalculateContract($input: CampaignInput!) {\n    calculateContract(input: $input) {\n      total\n      beforeDiscount\n      adjustments {\n        name\n        key\n        type\n        amount\n        applyDiscount\n      }\n      services {\n        pieces {\n          name\n          price\n        }\n        serviceName\n        basePrice\n        subsequentPrice\n        adjustments {\n          name\n          key\n          type\n          amount\n          applyDiscount\n        }\n        subTotal\n        beforeDiscount\n      }\n    }\n  }\n"): (typeof documents)["\n  query CalculateContract($input: CampaignInput!) {\n    calculateContract(input: $input) {\n      total\n      beforeDiscount\n      adjustments {\n        name\n        key\n        type\n        amount\n        applyDiscount\n      }\n      services {\n        pieces {\n          name\n          price\n        }\n        serviceName\n        basePrice\n        subsequentPrice\n        adjustments {\n          name\n          key\n          type\n          amount\n          applyDiscount\n        }\n        subTotal\n        beforeDiscount\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query clients($firstName: String!, $lastName: String!) {\n    clients(where: { firstName: { eq: $firstName }, lastName: { eq: $lastName } }) {\n      userId\n      firstName\n      lastName\n    }\n  }\n"): (typeof documents)["\n  query clients($firstName: String!, $lastName: String!) {\n    clients(where: { firstName: { eq: $firstName }, lastName: { eq: $lastName } }) {\n      userId\n      firstName\n      lastName\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query broadcasters($firstName: String!, $lastName: String!) {\n    broadcasters(where: { firstName: { eq: $firstName }, lastName: { eq: $lastName } }) {\n      userId\n      firstName\n      lastName\n    }\n  }\n"): (typeof documents)["\n  query broadcasters($firstName: String!, $lastName: String!) {\n    broadcasters(where: { firstName: { eq: $firstName }, lastName: { eq: $lastName } }) {\n      userId\n      firstName\n      lastName\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;